print("What is your name human?")
name = input()
print("\nHow old are you? (in year)")
age = input()
print("\nHow tall are you?(in meters)")
meters = input()
print("\nHow much do you weight?(in kilograms)")
kilograms = input()
print("\n your are"+str(age), "years old and your bmi is")
